### ISSUE TITLE
Blank Pages

### ISSUE THREAD

**Issue by sherifkayad** [viqueen/confluence-static-site#77]
Hi,

after extracting the content succesfully and building I end up by blank pages. What might be a reason for that?

In the console I see something like:
![image](https://github.com/viqueen/confluence-static-site/assets/8362784/0b69f8bf-0e7d-49a2-af7f-602afccc3eab)

Could it be node version related? .. I am using node `18.19.0` on Ubuntu

**Comment by viqueen** [comment]
I have just tested now with Node v18.19.0 (npm v10.2.3) on a fresh master branch.
It does work for me.
Are you targeting confluence cloud or a confluence server/data-center instance ? This site generator works for confluence cloud only .

I can see that the visual regression tests are failing , not sure why , imma give them a fix and hopefully that gives me a lead into why it is not working for you.

**Comment by sherifkayad** [comment]
@viqueen I am using Confluence Cloud with a space I created to test the export. Any hints on what I might try to do / how to debug further?

BTW can you send me the list of commands you are running .. and what exact variables are you using in your .env file? .. I see in the docs that doesn't match 100% what was mentioned in your example repo nor an issue I have seen.

**Comment by viqueen** [comment]
@sherifkayad take a look at this thread here https://stackoverflow.com/questions/65109315/hard-dealing-with-error-minified-react-error-321-reactjs/75607659#75607659 , some people suggest they fixed the issue by disabling their loom extension 🤷‍♀️ .

Using this repo as is, I do: 
```
yarn build
./cli extract <spaceKey>
./cli build <spaceKey> --serve
```

My env file contains the following : 
- needed to extract content and assets
```
CONFLUENCE_SITE_NAME=<name>.atlassian.net
CONFLUENCE_USERNAME=<atlassian-id-email-address>
CONFLUENCE_API_TOKEN=<api-token>
CONFLUENCE_CLOUD_TOKEN=<tenant.session.token> 
```
(tenant.session.token can be found in cookie set on `/gateway/api` calls, you'll have to fiddle around with the network tab to extract it) 


- needed for seo/analytics and rewriting internal urls in inlined links
```
TARGET_SITE=<prod-host-url>
TWITTER_SITE=<twitter-handle>
GOOGLE_ANALYTICS_TRACKING=<>
```

**Comment by sherifkayad** [comment]
@viqueen thanks a lot for your reply and the details. Let me give it another try and let you know 😉

**Comment by sherifkayad** [comment]
@viqueen I tried again with serving locally from the local webpack server .. Still the React erros is there .. now with a more meaningful message:
```
react.development.js:1465 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1465:13)
    at useState (react.development.js:1496:20)
    at SkipLinksController (skip-link-controller.js:42:66)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20069:13)
    at beginWork (react-dom.development.js:21582:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27446:7)
```

And:
```
The above error occurred in the <SkipLinksController> component:

    at SkipLinksController (webpack://confluence-exporter/./node_modules/@atlaskit/page-layout/dist/esm/controllers/skip-link-controller.js?:41:23)
    at PageLayout (webpack://confluence-exporter/./node_modules/@atlaskit/page-layout/dist/esm/components/slots/page-layout.js?:50:34)
    at div
    at StaticSite

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

Any idea? .. BTW I tried from a completely different browser and still no luck

**Comment by viqueen** [comment]
@sherifkayad those errors tell me that there may be issues with the dependencies.
May I ask how you installed them ?
Did you follow the steps in `CONTRIBUTING.md` file by any chance ?

If you've used `npm` instead of `yarn` , you will run into a lot of dependency issues that push you to update to latest versions of atlaskit modules , and that's when we hit this sort of react issues

**Comment by sherifkayad** [comment]
@viqueen I was using `npm install`. I switched to using `yarn` as you documented .. and my `package.json` looks like follows:
```json
{
  "name": "confluence-exporter",
  "version": "1.0.0",
  "description": "Export Confluence to a Static Website",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "@labset/confluence-static-site": "^1.2.0"
  }
}
```

With `yarn`, I still got problems with the build. Let me walk you through my commands and their result.

1. `yarn` => works fine, however, I see some warnings e.g. `@atlaskit/renderer > @atlaskit/editor-common > @atlaskit/profilecard > @atlaskit/give-kudos > @atlaskit/drawer@7.5.2" has incorrect peer dependency "react@^16.8.0`
2. `yarn confsite extract <MY_SPACE>` => works perfectly fine!
3. `yarn confsite build <MY_SPACE>` => results in errors e.g.:
```
 Field 'browser' doesn't contain a valid alias configuration
 @ ./node_modules/@labset/confluence-static-site/dist/site/content/content-renderer.js
 @ ./node_modules/@labset/confluence-static-site/dist/site/site-content.js 89:25-62 
 @ ./node_modules/@labset/confluence-static-site/dist/site/index.js 25:21-46        

webpack 5.90.1 compiled with 3 errors in 59989 ms
```

**Comment by viqueen** [comment]
@sherifkayad hei hei , finally had some time to replicate the issue and look into it.

so looks like atlaskit has released some breaking changes across some of their modules, and the use of version ranges leads to some of those transitive dependencies popping into our dependency graph.

can you please try using the following in your package.json

```
"resolutions": {
    "@atlaskit/editor-common": "72.4.0"
  },
  "devDependencies": {
    "@labset/confluence-static-site": "^1.3.0"
  }
```

the resolutions part ensures we're getting all the deps compatible for that version of editor-common that `confluence-static-site` relies on.
that should fix the issues you're seeing.

**Comment by sherifkayad** [comment]
@viqueen thanks a lot for looking into it. I re-ran `yarn` with the suggested change in the `package.json`, however, I still have the same error when I do `yarn confsite build <MY_SPACE>`

**Comment by viqueen** [comment]
Hmm odd , that fixed it on my side . Did you do a clean build ? Removing node_modules and yarn.lock ?

I will take another look in the morning, thanks for your patience and apologies for all the inconvenience 🙏

**Comment by sherifkayad** [comment]
Yeah I did so .. I deleted both before running `yarn` again.

Actually thanks to you and your prompt response 🙂

**Comment by viqueen** [comment]
Alright, I've tested a million times with the following config , turns out there were some other dependencies that needed pinning ... yey atlaskit 🥳 

```
 "resolutions": {
    "@atlaskit/editor-common": "72.4.0",
    "@atlaskit/emoji" : "67.3.0",
    "@atlaskit/media-core": "34.1.4",
    "@atlaskit/renderer": "107.0.0"
  },
  "devDependencies": {
    "@labset/confluence-static-site": "^1.3.0"
  }
```

Hopefully this works for you too

**Comment by sherifkayad** [comment]
@viqueen works like a charm now! Thank you so much. Please feel free to close this issue.
